</div>
</el-main>
</el-container>
</el-container>
</div>
</body>
</html>
<script type="text/javascript" src="/template/static/master/framework/vue.min.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/master/framework/jquery.min.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/master/element-ui/element-ui.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/master/library/core/cookie.min.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/master/library/core/CryptoJS.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/master/library/utils/app.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/script/mixins.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>
<script type="text/javascript" src="/template/static/script/component.js?v=<?php echo time().mt_rand(10000,20000)?>"></script>