<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <!-- 优先使用 IE 最新版本和 Chrome -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <!-- 浏览器内核控制：webkit|ie-comp|ie-stand -->
        <meta name="renderer" content="webkit">
        <!-- 禁止浏览器从本地计算机的缓存中访问页面内容：这样设定，访问者将无法脱机浏览。 -->
        <meta http-equiv="Pragma" content="no-cache">
        <!--
             * ================================================================================
             * SEO优化
             * ================================================================================
        -->
        <!-- 关键词 -->
        <meta name="keywords" content="管理后台系统" />
        <!-- 描述:150个字以内 -->
        <meta name="description" content="150 words" />
        <!-- 搜索引擎索引方式：文件将被检索，页面上的链接不可以被查询 线上：index,follow；测试：none -->
        <meta name="robots" content="none" />
        <meta name="google" content="none" />
        <meta name="googlebot" content="none" />
        <meta name="verify" content="none" />
        <!-- 作者：标梵互动 -->
        <meta name="author" content="管理后台系统" />
        <!--
             * ================================================================================
             * 移动设备
             * ================================================================================
        -->
        <!-- 能优化移动浏览器的显示。-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no" />
        <!-- WebApp全屏模式：伪装app，离线应用。 -->
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <!-- 隐藏状态栏/设置状态栏颜色：只有在开启WebApp全屏模式时才生效。 -->
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <!-- 添加到主屏后的标题 -->
        <meta name="apple-mobile-web-app-title" content="管理后台系统">
        <!-- 忽略数字自动识别为电话号码 -->
        <meta content="telephone=no" name="format-detection" />
        <!-- 忽略识别邮箱 -->
        <meta content="email=no" name="format-detection" />
        <!-- <meta name="apple-itunes-app" content="app-id=myAppStoreID, affiliate-data=myAffiliateData, app-argument=myURL">加智能 App 广告条 Smart App Banner：告诉浏览器这个网站对应的app。 -->
        <!-- 针对手持设备优化，主要是针对一些老的不识别viewport的浏览器，比如黑莓 -->
        <meta name="HandheldFriendly" content="true">
        <!-- 微软的老式浏览器 -->
        <meta name="MobileOptimized" content="320">
        <!-- uc强制竖屏 -->
        <meta name="screen-orientation" content="portrait">
        <!-- QQ强制竖屏 -->
        <meta name="x5-orientation" content="portrait">
        <!-- UC强制全屏 -->
        <meta name="full-screen" content="yes">
        <!-- QQ强制全屏 -->
        <meta name="x5-fullscreen" content="true">
        <!-- UC应用模式 -->
        <meta name="browsermode" content="application">
        <!-- QQ应用模式 -->
        <meta name="x5-page-mode" content="app">
        <!-- windows phone 点击无高光 -->
        <meta name="msapplication-tap-highlight" content="no">
        <title>位尔多管理后台系统</title>

        <link rel="stylesheet" type="text/css" href="/template/static/master/element-ui/theme/element-ui.css?v=<?php echo time().mt_rand(10000,20000)?>">
        <link rel="stylesheet" type="text/css" href="/template/static/style/main/style.css?v=<?php echo time().mt_rand(10000,20000)?>">
        <link rel="stylesheet" type="text/css" href="/template/static/style/style.css?v=<?php echo time().mt_rand(10000,20000)?>">
        <link rel="stylesheet" href="//at.alicdn.com/t/font_1513911_ugai6ly14jl.css">
        <link rel="stylesheet" href="/template/static/style/font-awesome/font-awesome.min.css">
    </head>
    <body>
        <div id="app">
            <el-container class="ym-container" v-cloak id="layouts-container">
                <el-aside :style="layouts.left.show ? (layouts.collapse.show ? {width:'64px'} : {width:'210px'}) : {width:'1px'}" class="container-aside">
                    <div class="container-aside-logo" :style="layouts.collapse.show ? {width:'64px'} : {width:'210px'}">
                        <el-avatar shape="square" size="medium"></el-avatar>
                        <span class="title" v-show="!layouts.collapse.show">位尔多管理系统</span>
                    </div>
                    <div class="container-aside-menu" v-if="layouts.left.show">
                        <el-menu
                            :default-active="layouts.left.active"
                            class="left-menu"
                            @select="layoutsLeftMenuEvent"
                            :unique-opened="true"
                            :collapse="layouts.collapse.show"
                        >
                            <template v-if="layouts.left.show">
                                <template v-for="items in layouts.left.menus">
                                    <el-menu-item :index="items.id" v-if="!items.children" :item="items">{{items.name}}</el-menu-item>
                                    <el-submenu :index="items.id" :item="items" v-else>
                                        <template slot="title">{{items.name}}</template>
                                        <el-menu-item v-for="children in items.children" :index="children.id" :item="children">{{children.name}}</el-menu-item>
                                    </el-submenu>
                                </template>
                            </template>
                        </el-menu>
                    </div>
                </el-aside>
                <el-container>
                    <el-header class="container-menu-header" :style="layouts.left.show ? {marginLeft:'0'} : {marginLeft:'204px'}">
                        <el-menu
                            class="header-menu"
                            mode="horizontal"
                            :default-active="layouts.header.active"
                            @select="layoutsHeaderMenuEvent"
                            background-color="#2f4050"
                            text-color="#fff"
                            active-text-color="#FF7500"
                        >
                            <div class="header-collapse" @click="layoutsCollapseEvent" v-if="layouts.left.show">
                                <i class="el-icon-s-fold"></i>
                            </div>
                            <template v-if="layouts.header.show">
                                <template v-for="items in layouts.header.menus">
                                    <el-menu-item :index="items.id" v-if="!items.children || items.children.length < 1" :item="items" >{{items.name}}</el-menu-item>
                                    <el-submenu :index="items.id" :item="items" v-else>
                                        <template slot="title">{{items.name}}</template>
                                        <el-menu-item v-for="children in items.children" :index="children.id" :item="children" >{{children.name}}</el-menu-item>
                                    </el-submenu>
                                </template>
                            </template>
                        </el-menu>
                        <div class="header-dropdown">
                            <el-dropdown>
                                <span class="el-dropdown-link">
                                    NuoCoo <i class="el-icon-arrow-down el-icon--right"></i>
                                </span>
                                <el-dropdown-menu slot="dropdown">
                                    <el-dropdown-item>修改密码</el-dropdown-item>
                                    <el-dropdown-item>安全退出</el-dropdown-item>
                                </el-dropdown-menu>
                            </el-dropdown>
                        </div>
                    </el-header>
                    <div style="width: 100%;height: 39px;" v-if="layouts.tabs.show">
                        <div style="position: fixed;right: 76px;" :style="layouts.left.show ? (layouts.collapse.show ? {left:'64px'} : {left:'210px'}) : {left:'0px'}">
                            <el-tabs type="border-card" closable
                                    v-model="layouts.tabs.active"
                                    class="container-tabs"
                                    :before-leave="layoutsTabsMenuBeforeEvent"
                                    @tab-click="layoutsTabsMenuClickEvent"
                                    @tab-remove='layoutsTabsMenuCloseEvent'
                            >
                                <el-tab-pane v-for="items in layouts.tabs.menus" :label="items.name" :item="items" :name="items.id"></el-tab-pane>
                            </el-tabs>
                        </div>

                        <div class="container-tabs-dropdown">
                            <el-dropdown @command="layoutsTabsDropdownCommand">
                                <span class="el-dropdown-link">
                                    操作 <i class="el-icon-arrow-down el-icon--right"></i>
                                </span>
                                <el-dropdown-menu slot="dropdown" >
                                    <el-dropdown-item command="close-current">关闭当前</el-dropdown-item>
                                    <el-dropdown-item command="close-all">关闭全部</el-dropdown-item>
                                    <el-dropdown-item command="refresh-page" divided>刷新页面</el-dropdown-item>
                                </el-dropdown-menu>
                            </el-dropdown>
                        </div>
                    </div>

                    <el-main class="container-main" :style="layouts.style.containerMain">
                        <div class="container-main-box" :style="layouts.style.containerMainContent">
