<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <!-- 优先使用 IE 最新版本和 Chrome -->
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <!-- 浏览器内核控制：webkit|ie-comp|ie-stand -->
        <meta name="renderer" content="webkit">
        <!-- 禁止浏览器从本地计算机的缓存中访问页面内容：这样设定，访问者将无法脱机浏览。 -->
        <meta http-equiv="Pragma" content="no-cache">
        <!--
             * ================================================================================
             * SEO优化
             * ================================================================================
        -->
        <!-- 关键词 -->
        <meta name="keywords" content="管理后台系统" />
        <!-- 描述:150个字以内 -->
        <meta name="description" content="150 words" />
        <!-- 搜索引擎索引方式：文件将被检索，页面上的链接不可以被查询 线上：index,follow；测试：none -->
        <meta name="robots" content="none" />
        <meta name="google" content="none" />
        <meta name="googlebot" content="none" />
        <meta name="verify" content="none" />
        <!-- 作者：标梵互动 -->
        <meta name="author" content="管理后台系统" />
        <!--
             * ================================================================================
             * 移动设备
             * ================================================================================
        -->
        <!-- 能优化移动浏览器的显示。-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0,maximum-scale=1.0, user-scalable=no" />
        <!-- WebApp全屏模式：伪装app，离线应用。 -->
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <!-- 隐藏状态栏/设置状态栏颜色：只有在开启WebApp全屏模式时才生效。 -->
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <!-- 添加到主屏后的标题 -->
        <meta name="apple-mobile-web-app-title" content="管理后台系统">
        <!-- 忽略数字自动识别为电话号码 -->
        <meta content="telephone=no" name="format-detection" />
        <!-- 忽略识别邮箱 -->
        <meta content="email=no" name="format-detection" />
        <!-- <meta name="apple-itunes-app" content="app-id=myAppStoreID, affiliate-data=myAffiliateData, app-argument=myURL">加智能 App 广告条 Smart App Banner：告诉浏览器这个网站对应的app。 -->
        <!-- 针对手持设备优化，主要是针对一些老的不识别viewport的浏览器，比如黑莓 -->
        <meta name="HandheldFriendly" content="true">
        <!-- 微软的老式浏览器 -->
        <meta name="MobileOptimized" content="320">
        <!-- uc强制竖屏 -->
        <meta name="screen-orientation" content="portrait">
        <!-- QQ强制竖屏 -->
        <meta name="x5-orientation" content="portrait">
        <!-- UC强制全屏 -->
        <meta name="full-screen" content="yes">
        <!-- QQ强制全屏 -->
        <meta name="x5-fullscreen" content="true">
        <!-- UC应用模式 -->
        <meta name="browsermode" content="application">
        <!-- QQ应用模式 -->
        <meta name="x5-page-mode" content="app">
        <!-- windows phone 点击无高光 -->
        <meta name="msapplication-tap-highlight" content="no">

        <title>位尔多管理后台系统</title>
        <link rel="stylesheet" type="text/css" href="/template/static/master/element-ui/theme/element-ui.css?v=<?php echo time().mt_rand(10000,20000)?>">
        <link rel="stylesheet" type="text/css" href="/template/static/style/main/style.css?v=<?php echo time().mt_rand(10000,20000)?>">
        <link rel="stylesheet" type="text/css" href="/template/static/style/style.css?v=<?php echo time().mt_rand(10000,20000)?>">
        <link rel="stylesheet" href="//at.alicdn.com/t/font_1513911_ugai6ly14jl.css">
    </head>
    <body>
        <div id="app">
