<?php Yaf_Loader::import(VIEW_PATH . '/layout/header.phtml'); ?>
    <ul v-for="x in 14" style="width: 100%;height: 40px;float: left;">
        <template  v-for="y in 34">
            <li v-if='road[y]' class="parking-list-road">
                <i class='el-icon-bottom' style="font-size: 18px;" v-if='road[x]'></i>
                <i class='el-icon-bottom1' style="font-size: 18px;" v-else></i>
            </li>
            <li v-else @click="parkingClickEvent($event, x, y)" class="parking-list" >
                <i class='iconfont icon-qiche' style="font-size: 23px;" :class="{statusColor:parkingData[x+'c'+y+'a'].status}"></i>
            </li>
        </template>
    </ul>
<?php Yaf_Loader::import(VIEW_PATH . '/layout/footer.phtml'); ?>
<script>
   var $NuoCoo = new Vue({
        el: '#app',
       mixins: [$layout],
        data: {
            activeIndex: '1',
			road:{'2':1,'5':1,'8':1,'11':1,'14':1,'17':1,'20':1,'23':1,'26':1,'29':1,'32':1,'34':1},
			parkingData:[]
        },
        methods: {
            parkingClickEvent:function(e, x, y){
               var that = this;

               that.$set(that.parkingData[x+'c'+y+'a'], 'status', 1);
                console.log(that.parkingData[x + 'c' + y + 'a']);
                // console.log(that.parkingData);
                // that.$set(that.parkingData, [x+'c'+y+'a'], {i:x,j:y,status:true});
                // console.log(that.parkingData[]);
            },

			parkingMouseoverEvent:function(e, x, y){
				console.log(e, x, y);
			},
			parkingMouseoutEvent:function(e, x, y){
				console.log(e, x, y);
			},

            handleSelect(key, keyPath) {
                $(".container-content").load('/index/forms');
                console.log(key, keyPath);
            },
            handleOpen(key, keyPath) {
                $(".container-content").load('/forms');
                console.log(key,keyPath);
                console.log(key, keyPath);
            },
            handleClose(key, keyPath) {
                console.log(key, keyPath);
            }
        },
       mounted: function () {
           var that = this;

       },
		beforeCreate:function(){
			console.log('beforecreate');
		},

		created:function(){
			for(var i = 1; i <= 14; i++){
			    var j = 1;
				for(j; j <= 34; j++){
                    this.parkingData[i+'c'+j+'a'] = {i:i,j:j,status:false};
				}
			}

		}
    })
</script>
