<?php Yaf_Loader::import(VIEW_PATH.'/layout/header.phtml'); ?>
<?php Yaf_Loader::import(VIEW_PATH.'/layout/main.phtml'); ?>
<el-button size="medium" type="primary" @click="components.dialogFixed.dialog = true">打开dialogFixed</el-button>

<el-button size="medium" type="primary" @click="components.dialogAuto.dialog = true">打开dialogAuto</el-button>

<el-button size="medium" type="primary" @click="$import.openEvent">打开导入文件</el-button>

<?php Yaf_Loader::import(VIEW_PATH.'/components/dialog-auto.phtml'); ?>
<?php Yaf_Loader::import(VIEW_PATH.'/components/dialog-fixed.phtml'); ?>
<?php Yaf_Loader::import(VIEW_PATH.'/components/import-files.phtml'); ?>
<?php Yaf_Loader::import(VIEW_PATH.'/layout/footer.phtml'); ?>
<script>
    var $App = new Vue({
        el: '#app',
        mixins: [$layout],
        data: {
			components:{
                import:{options:{accept:'txt,png,jpg,pneg',size:'5'},callback:'importCallback',action:
                {url:'', callback:''}
            },
            }
        },
        methods: {
            importCallback:function(result){
                console.log(result);
            }
        },
        mounted: function () {
            var that = this;

        },
        beforeCreate:function(){
           
        },

        created:function(){


        }
    })
</script>
