<?php Yaf_Loader::import(VIEW_PATH.'/layout/header.phtml'); ?>
<?php Yaf_Loader::import(VIEW_PATH.'/layout/main.phtml'); ?>
<el-button type="primary" @click="dialogVisible = true">主要按钮</el-button>
<el-dialog
        title="提示"
        :visible.sync="dialogVisible"
        width="30%"
        custom-class="ym-dialog fixed"
        :before-close="handleClose"
>
    <span>这是一段信息</span>
    <span slot="footer" class="dialog-footer">
    <el-button @click="dialogVisible = false">取 消</el-button>
    <el-button type="primary" @click="dialogVisible = false">确 定</el-button>
  </span>
</el-dialog>

<?php Yaf_Loader::import(VIEW_PATH.'/layout/footer.phtml'); ?>
<script>
    var $NuoCoo = new Vue({
        el: '#app',
        mixins: [$layout],
        data: {
            dialogVisible: false
        },
        methods: {
            handleClose(done) {
                this.$confirm('确认关闭？')
                    .then(_ => {
                        done();
                    })
                    .catch(_ => {});
            }
        },
        mounted: function () {
            var that = this;

        },
        beforeCreate:function(){
            console.log('beforecreate');
        },

        created:function(){


        }
    })
</script>
