<el-dialog
        title="提示"
		:close-on-click-modal="false"
        :visible.sync="components.dialogFixed.dialog"
        width="30%"
		top="15vh"
		:show-close="true"
       :lock-scroll="false"
	    append-to-body
        custom-class="ym-dialog fixed"
>
 <!-- fixed--> 
    <div class="ym-dialog-main" :style="layouts.style.dialogFixed">
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
    </div>
    <span slot="footer" class="dialog-footer">
		<el-button type="primary" @click="components.dialogFixed.dialog = false" size="medium">确 定</el-button>
		<el-button @click="dialogVisible =components.dialogFixed.dialog = false" size="medium">取 消</el-button>
  </span>
</el-dialog>