<el-dialog
        title="提示"
		:close-on-click-modal="false"
        :visible.sync="components.dialogAuto.dialog"
        width="30%"
		top="15vh"
		:show-close="true"
       :lock-scroll="false"
	    append-to-body
        custom-class="ym-dialog auto"
>
 <!-- fixed--> 
    <div class="ym-dialog-main" :style="layouts.style.dialogAuto">
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasdasfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
        <div style="height:20px">asfadsfasdfasd</div>
    </div>
    <span slot="footer" class="dialog-footer">
    <el-button @click="dialogVisible =components.dialogAuto.dialog = false" size="medium">取 消</el-button>
    <el-button type="primary" @click="components.dialogAuto.dialog = false" size="medium">确 定</el-button>
  </span>
</el-dialog>